### ISSUE TITLE
The parser is not able to handle Having count 

### ISSUE THREAD

**Issue by victorsantoss** [dazinator/SQLGeneration#9]
Hey there,

I put this issue on the main rep and since we both seems to be taking a look at this code apart from the original owner I'm sharing this with you too.

A simple query is not properly handled by the parser. 

| Original Query | Output query |
| --- | --- |
| SELECT 1 HAVING count(1) = 1 | SELECT 1 HAVING count(1) |

This one is even better:

| Original Query | Output query |
| --- | --- |
| SELECT 1 AS field HAVING count(1) = 1 order by field | SELECT 1 AS field HAVING count(1) |

This can be easily reproduced on Test Method: TestSelect_Having

**Comment by dazinator** [comment]
Hi - thanks for reporting this - I see @jehugaleahsa has fixed this now. I haven't done much work on SQLGeneration for a while as this fork is currently fulfilling all of my needs.

Changes in this fork are unlikely to ever be merged back into the original (Travis's) repo due to my lack of branching (I was learning git at the time) to seperate things out into small manageable PR's that can be merged easier. I have also added some things which Travis may not want in the original repo at all as they were features added for my own ends like batching. So I would say it's going to be better to address any bugs in the original repo, and then anyone who forks can benefit from them also (should they want to)

Anyway - glad it's sorted ;)
